"""
Default email template definitions — extracted from routes/system_emails.py
to break the circular dependency with services/email_service.py.
"""

DEFAULT_EMAIL_TEMPLATES = {
    "welcome": {
        "id": "welcome",
        "name": "Welcome Email",
        "description": "Sent when a new user account is created",
        "subject": "Welcome to {company_name} - Your Login Credentials",
        "show_icon": True,
        "icon_type": "shield",
        "custom_icon_url": None,
        "header_title": "Welcome to {company_name}!",
        "header_subtitle": "Your account has been created",
        "greeting_template": "Hello {user_name},",
        "body_template": "An administrator has created an account for you.",
        "cta_text": "Login to Your Account",
        "cta_url_template": "{login_url}",
        "show_cta": True,
        "footer_text": "{company_name} Security Training Platform",
        "show_security_warning": True,
        "security_warning_text": "Security: Change your password after first login.",
        "primary_color": "#D4A836",
        "variables": ["user_name", "user_email", "password", "login_url", "company_name"]
    },
    "password_reset": {
        "id": "password_reset",
        "name": "Password Reset",
        "description": "Sent when an admin resets a user's password",
        "subject": "{company_name} - Your Password Has Been Reset",
        "show_icon": True,
        "icon_type": "key",
        "custom_icon_url": None,
        "header_title": "Password Reset",
        "header_subtitle": "Your password has been changed",
        "greeting_template": "Hello {user_name},",
        "body_template": "An administrator has reset your password.",
        "cta_text": "Login with New Password",
        "cta_url_template": "{login_url}",
        "show_cta": True,
        "footer_text": "{company_name} Security Training Platform",
        "show_security_warning": True,
        "security_warning_text": "If you didn't request this, contact your administrator.",
        "primary_color": "#D4A836",
        "variables": ["user_name", "user_email", "password", "login_url", "company_name"]
    },
    "forgot_password": {
        "id": "forgot_password",
        "name": "Forgot Password",
        "description": "Sent when a user requests password reset",
        "subject": "{company_name} - Password Reset Request",
        "show_icon": True,
        "icon_type": "key",
        "custom_icon_url": None,
        "header_title": "Password Reset Request",
        "header_subtitle": "Click below to reset your password",
        "greeting_template": "Hello {user_name},",
        "body_template": "We received a request to reset your password. Click the button below to create a new password.",
        "cta_text": "Reset Password",
        "cta_url_template": "{reset_url}",
        "show_cta": True,
        "footer_text": "{company_name} Security Training Platform",
        "show_security_warning": True,
        "security_warning_text": "If you didn't request this, you can safely ignore this email.",
        "primary_color": "#D4A836",
        "variables": ["user_name", "user_email", "reset_url", "company_name"]
    },
    "training_assignment": {
        "id": "training_assignment",
        "name": "Training Assignment",
        "description": "Sent when training is assigned to a user",
        "subject": "{company_name} - New Security Training Assigned",
        "show_icon": True,
        "icon_type": "alert",
        "custom_icon_url": None,
        "header_title": "Training Required",
        "header_subtitle": "You have been assigned security training",
        "greeting_template": "Hello {user_name},",
        "body_template": "You have been assigned new security training: {module_name}. Please complete it as soon as possible.",
        "cta_text": "Start Training",
        "cta_url_template": "{training_url}",
        "show_cta": True,
        "footer_text": "{company_name} Security Training Platform",
        "show_security_warning": False,
        "security_warning_text": "",
        "primary_color": "#D4A836",
        "variables": ["user_name", "user_email", "module_name", "training_url", "company_name"]
    },
    "contact_form_notification": {
        "id": "contact_form_notification",
        "name": "Contact Form Notification",
        "description": "Sent to admins when someone submits a contact form",
        "subject": "New Contact Form Submission from {sender_name}",
        "show_icon": True,
        "icon_type": "mail",
        "custom_icon_url": None,
        "header_title": "New Contact Form Submission",
        "header_subtitle": "Someone has contacted you via the website",
        "greeting_template": "Hello Admin,",
        "body_template": "You have received a new contact form submission.\n\n<strong>Name:</strong> {sender_name}<br><strong>Email:</strong> {sender_email}<br><strong>Organization:</strong> {organization}<br><strong>Phone:</strong> {phone}<br><br><strong>Message:</strong><br>{message}",
        "cta_text": "View All Submissions",
        "cta_url_template": "{dashboard_url}/form-submissions",
        "show_cta": True,
        "footer_text": "{company_name} Security Training Platform",
        "show_security_warning": False,
        "security_warning_text": "",
        "primary_color": "#D4A836",
        "variables": ["sender_name", "sender_email", "organization", "phone", "message", "dashboard_url", "company_name"]
    },
    "access_request_notification": {
        "id": "access_request_notification",
        "name": "Access Request Notification",
        "description": "Sent to admins when someone requests access",
        "subject": "New Access Request from {requester_name}",
        "show_icon": True,
        "icon_type": "shield",
        "custom_icon_url": None,
        "header_title": "New Access Request",
        "header_subtitle": "Someone has requested platform access",
        "greeting_template": "Hello Admin,",
        "body_template": "A new access request has been submitted.\n\n<strong>Name:</strong> {requester_name}<br><strong>Email:</strong> {requester_email}<br><strong>Organization:</strong> {organization}<br><strong>Phone:</strong> {phone}<br><br><strong>Reason:</strong><br>{message}",
        "cta_text": "Review Request",
        "cta_url_template": "{dashboard_url}/form-submissions",
        "show_cta": True,
        "footer_text": "{company_name} Security Training Platform",
        "show_security_warning": False,
        "security_warning_text": "",
        "primary_color": "#D4A836",
        "variables": ["requester_name", "requester_email", "organization", "phone", "message", "dashboard_url", "company_name"]
    },
    "access_request_approved": {
        "id": "access_request_approved",
        "name": "Access Request Approved",
        "description": "Sent to users when their access request is approved",
        "subject": "Your Access Request Has Been Approved - {company_name}",
        "show_icon": True,
        "icon_type": "check",
        "custom_icon_url": None,
        "header_title": "Access Approved!",
        "header_subtitle": "Your account has been created",
        "greeting_template": "Hello {user_name},",
        "body_template": "Great news! Your access request has been approved and your account has been created.\n\nYou can now log in using the credentials below:\n\n<strong>Email:</strong> {user_email}<br><strong>Temporary Password:</strong> {password}",
        "cta_text": "Login Now",
        "cta_url_template": "{login_url}",
        "show_cta": True,
        "footer_text": "{company_name} Security Training Platform",
        "show_security_warning": True,
        "security_warning_text": "Please change your password after your first login.",
        "primary_color": "#D4A836",
        "variables": ["user_name", "user_email", "password", "login_url", "company_name"]
    }
}
